
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int CONMUTATIVE = 10;
  public static final int IDENTITY = 11;
  public static final int COMBINES = 24;
  public static final int USES_FUNC = 17;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int EQUAL = 23;
  public static final int SEMI = 2;
  public static final int NAME = 29;
  public static final int CONCAT = 20;
  public static final int DISTRIBUTIVE = 13;
  public static final int LPAREN = 7;
  public static final int EXP = 25;
  public static final int PROP_NAME = 28;
  public static final int COMMA = 27;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int COMMON_FACTOR = 14;
  public static final int OPERATION = 16;
  public static final int USES_CONSTANTS = 22;
  public static final int ELEMENT = 15;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQUIVALENT = 26;
  public static final int ASOCIATIVE = 9;
  public static final int PERMUTE = 18;
  public static final int ZERO = 12;
  public static final int SUBLIST = 19;
  public static final int DETECT = 21;
  public static final int UMINUS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "ASOCIATIVE",
  "CONMUTATIVE",
  "IDENTITY",
  "ZERO",
  "DISTRIBUTIVE",
  "COMMON_FACTOR",
  "ELEMENT",
  "OPERATION",
  "USES_FUNC",
  "PERMUTE",
  "SUBLIST",
  "CONCAT",
  "DETECT",
  "USES_CONSTANTS",
  "EQUAL",
  "COMBINES",
  "EXP",
  "EQUIVALENT",
  "COMMA",
  "PROP_NAME",
  "NAME",
  "NUMBER"
  };
}

